### ISSUE TITLE
configtype file is broken because some properties still use underscore

### ISSUE THREAD

**Issue by claudobahn** [evertrue/exhibitor-cookbook#39]
When replacing `render_properties_file` with `properties_config` a few properties were missed (lines 85-88 in `recipes/default.rb`) which contain the zookeeper directories.

Those specific properties are needed in order for Zookeeper to start up, so Exhibitor sits in latent mode.

Basically all that's needed is to replace underscores with hyphens and generate a new release. As it stands right now, the cookbook is non-functional for file based configs.

**Comment by jeffbyrnes** [comment]
Thanks for catching this, @claudobahn. I’ll see about shipping a fix ASAP.
