### ISSUE TITLE
Issues building the exhibitor immage

### ISSUE THREAD

**Issue by jedi132000** [evertrue/exhibitor-cookbook#40]
I am running into issues with the cookbook. it gives me a "Could not satisfy version constraints for: zookeeper". I made sure i had a working zookeeper and all the other dependencies that go with the build of exhibitor. Kindly help!!!.. 
My zookeeper build came from your repo, and that was successful.
Thanks.

zookeeper (7.1.0)
maven ~> 2.2
et_gradle ~> 2.0
magic ~> 1.5
runit ~> 1.7
java ~> 1.35
build-essential >= 0.0.0

**Comment by jeffbyrnes** [comment]
@jedi132000 I’m not sure I understand what you mean by “I had a working zookeeper”. That error you’re seeing comes from Berkshelf, which really only requires that you attempt to use the exhibitor cookbook in some fashion.

What does your cookbook’s metadata look like? Do you have a repo for it somewhere that I can look at?

What do you mean by “zookeeper build”? Or “building the exhibitor immage [sic]”? There’s no need to do any building of anything; cookbooks are to be used as-is, without modification.

I do apologize, the README for this cookbook is _sorely_ lacking. I’ll try to find some time soon to rewrite it to clearly lay out how best to use this cookbook, and perhaps provide some example usage.

**Comment by jedi132000** [comment]
I am sorry you misunderstood me, my intentions are to create a machine
image with the exhibitor cookbook. I have created a zookeeper image with
your cookbook and it works fine.The exhibitor cookbook has some
dependencies and one of them is zookeeper cookbook ~>5. I believe i have
all the dependent cookbooks, yet i am running into zookeeper version
dependency errors. Hope i have been able to explain myself, and thanks for
the timely and anticipated support.

**Comment by jedi132000** [comment]
{"name":"exhibitor","version":"2.0.1","description":"Installs Netflix Exhibitor","long_description":"","maintainer":"EverTrue","maintainer_email":"devops@evertrue.com","license":"Apache v2.0","platforms":{},"dependencies":{"build-essential":">= 0.0.0","java":"~> 1.35","runit":"~> 1.7","zookeeper":"~> 5.0","magic":"~> 1.5","et_gradle":"~> 2.0","maven":"~> 2.2"},"recommendations":{},"suggestions":{},"conflicting":{},"providing":{},"replacing":{},"attributes":{},"groupings":{},"recipes":{}}

The above is what my metadata.json looks like.

**Comment by jedi132000** [comment]
![image](https://cloud.githubusercontent.com/assets/14984442/16996604/042b478c-4e80-11e6-8eca-e637cc0d24eb.png)

**Comment by jeffbyrnes** [comment]
@jedi132000 you shouldn’t need to create an image from the `zookeeper` cookbook at all, as, like you say, this cookbook depends on `zookeeper` directly.

How are you building your images?

Generally speaking, you will want to create your own wrapper cookbook, to apply the settings appropriate for your usage of Exhibitor (and, by extension, ZooKeeper).

You can take a look at a new branch of our [`et_zookeeper` cookbook](https://github.com/evertrue/et_zookeeper-cookbook/tree/jeff/refactor-for-updated-exhibitor), which wraps this cookbook.

As for resolving the dependencies, you will want to use Berkshelf for that. It comes as part of [Chef DK](https://downloads.chef.io/chef-dk/), so you probably already have it, unless you’ve installed Chef via some other, less common means.

Berkshelf can also upload your wrapper cookbook & its dependencies to your Chef Server (if you are using a Chef Server).

**Comment by jedi132000** [comment]
let me give it a shot, thanks for the information.
